# Generated by Django 5.1.6 on 2025-05-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COMMITTEE_MASTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('COM_NAME', models.CharField(db_column='COM_NAME', max_length=200)),
                ('COM_FORMATION_DATE', models.DateField(db_column='COM_FORMATION_DATE')),
                ('ACTIVE', models.CharField(db_column='ACTIVE', max_length=1)),
                ('LEVEL1', models.CharField(db_column='LEVEL1', max_length=100)),
                ('REMARKS', models.TextField(blank=True, db_column='REMARKS', null=True)),
            ],
            options={
                'verbose_name': 'Committee Master',
                'verbose_name_plural': 'Committee Masters',
                'db_table': '"COMMITTEE"."COMMITTEE_MASTER"',
            },
        ),
        migrations.CreateModel(
            name='EVENT_TYPE_MASTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('MAIN_TYPE', models.CharField(db_column='MAIN_TYPE', max_length=100)),
                ('SUB_TYPE', models.CharField(db_column='SUB_TYPE', max_length=100)),
            ],
            options={
                'verbose_name': 'Event Type Master',
                'verbose_name_plural': 'Event Type Masters',
                'db_table': '"COMMITTEE"."EVENT_TYPE_MASTER"',
            },
        ),
        migrations.CreateModel(
            name='EVENT_MASTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('EVENT_NAME', models.CharField(db_column='EVENT_NAME', max_length=200)),
                ('EVENT_START_DT', models.DateField(db_column='EVENT_START_DT')),
                ('EVENT_END_DT', models.DateField(db_column='EVENT_END_DT')),
                ('EVENT_PURPOSE', models.TextField(db_column='EVENT_PURPOSE')),
                ('EVENT_REMARKS', models.TextField(blank=True, db_column='EVENT_REMARKS', null=True)),
                ('ORGANIZED_BY', models.ForeignKey(db_column='ORGANIZED_BY', on_delete=django.db.models.deletion.CASCADE, to='committee.committee_master')),
                ('EVENT_TYPE', models.ForeignKey(db_column='EVENT_TYPE', on_delete=django.db.models.deletion.CASCADE, to='committee.event_type_master')),
            ],
            options={
                'verbose_name': 'Event Master',
                'verbose_name_plural': 'Event Masters',
                'db_table': '"COMMITTEE"."EVENT_MASTER"',
            },
        ),
    ]
