# Generated by Django 5.1.6 on 2025-05-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_master',
            name='EVENT_PURPOSE',
            field=models.TextField(blank=True, db_column='EVENT_PURPOSE', null=True),
        ),
    ]
