name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 7889
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Debug Info
      run: |
        pwd
        ls -la
        python --version
        pip --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install -r backend/requirements.txt
        pip install -e .

    - name: Run Django migrations
      env:
        DJANGO_SETTINGS_MODULE: core.settings
        SECRET_KEY: 'django-insecure-test-key-123'
        DB_NAME: test_db
        DB_USER: postgres
        DB_PASSWORD: 7889
        DB_HOST: localhost
        DB_PORT: 5432
        DEBUG: 'True'
      run: |
        cd backend
        python manage.py migrate accounts 0001_initial --noinput
        python manage.py migrate accounts 0002_initial_data --noinput
        python manage.py migrate accounts --noinput
        python manage.py migrate core --noinput
        python manage.py migrate establishments --noinput
        python manage.py migrate academic --noinput
        python manage.py migrate faculty --noinput
        python manage.py migrate student --noinput
        python manage.py migrate --noinput

    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: core.settings
        SECRET_KEY: 'django-insecure-test-key-123'
        DB_NAME: test_db
        DB_USER: postgres
        DB_PASSWORD: 7889
        DB_HOST: localhost
        DB_PORT: 5432
        DEBUG: 'True'
      run: |
        cd backend
        python -m pytest